/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_amarantha_gpiomofo_service_gpio_ultrasonic_HCSR04 */

#ifndef _Included_net_amarantha_gpiomofo_service_gpio_ultrasonic_HCSR04
#define _Included_net_amarantha_gpiomofo_service_gpio_ultrasonic_HCSR04
#ifdef __cplusplus
extern "C" {
#endif
#undef net_amarantha_gpiomofo_service_gpio_ultrasonic_HCSR04_SAMPLES
#define net_amarantha_gpiomofo_service_gpio_ultrasonic_HCSR04_SAMPLES 1L
#undef net_amarantha_gpiomofo_service_gpio_ultrasonic_HCSR04_MIN_VALUE
#define net_amarantha_gpiomofo_service_gpio_ultrasonic_HCSR04_MIN_VALUE 200L
#undef net_amarantha_gpiomofo_service_gpio_ultrasonic_HCSR04_MAX_VALUE
#define net_amarantha_gpiomofo_service_gpio_ultrasonic_HCSR04_MAX_VALUE 13000L
/*
 * Class:     net_amarantha_gpiomofo_service_gpio_ultrasonic_HCSR04
 * Method:    init
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_net_amarantha_gpiomofo_service_gpio_ultrasonic_HCSR04_init
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     net_amarantha_gpiomofo_service_gpio_ultrasonic_HCSR04
 * Method:    measure
 * Signature: (II)J
 */
JNIEXPORT jlong JNICALL Java_net_amarantha_gpiomofo_service_gpio_ultrasonic_HCSR04_measure
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
