/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_amarantha_gpiomofo_service_gpio_WiringPiSetup */

#ifndef _Included_net_amarantha_gpiomofo_service_gpio_WiringPiSetup
#define _Included_net_amarantha_gpiomofo_service_gpio_WiringPiSetup
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_amarantha_gpiomofo_service_gpio_WiringPiSetup
 * Method:    wiringPiSetup
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_amarantha_gpiomofo_service_gpio_WiringPiSetup_wiringPiSetup
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
