/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_amarantha_gpiomofo_service_gpio_ultrasonic_HCSR04_Callback */

#ifndef _Included_net_amarantha_gpiomofo_service_gpio_ultrasonic_HCSR04_Callback
#define _Included_net_amarantha_gpiomofo_service_gpio_ultrasonic_HCSR04_Callback
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
