/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_amarantha_gpiomofo_trigger_UltrasonicSensor */

#ifndef _Included_net_amarantha_gpiomofo_trigger_UltrasonicSensor
#define _Included_net_amarantha_gpiomofo_trigger_UltrasonicSensor
#ifdef __cplusplus
extern "C" {
#endif
#undef net_amarantha_gpiomofo_trigger_UltrasonicSensor_TRIG
#define net_amarantha_gpiomofo_trigger_UltrasonicSensor_TRIG 0L
#undef net_amarantha_gpiomofo_trigger_UltrasonicSensor_ECHO
#define net_amarantha_gpiomofo_trigger_UltrasonicSensor_ECHO 1L
#undef net_amarantha_gpiomofo_trigger_UltrasonicSensor_SAMPLES
#define net_amarantha_gpiomofo_trigger_UltrasonicSensor_SAMPLES 5L
/*
 * Class:     net_amarantha_gpiomofo_trigger_UltrasonicSensor
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_amarantha_gpiomofo_trigger_UltrasonicSensor_init
  (JNIEnv *, jobject);

/*
 * Class:     net_amarantha_gpiomofo_trigger_UltrasonicSensor
 * Method:    measure
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_net_amarantha_gpiomofo_trigger_UltrasonicSensor_measure
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
