/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_amarantha_gpiomofo_display_lightboard_NativeLightBoard */

#ifndef _Included_net_amarantha_gpiomofo_display_lightboard_NativeLightBoard
#define _Included_net_amarantha_gpiomofo_display_lightboard_NativeLightBoard
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_amarantha_gpiomofo_display_lightboard_NativeLightBoard
 * Method:    initNative
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_net_amarantha_gpiomofo_display_lightboard_NativeLightBoard_initNative
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     net_amarantha_gpiomofo_display_lightboard_NativeLightBoard
 * Method:    setPoint
 * Signature: (IIZZ)V
 */
JNIEXPORT void JNICALL Java_net_amarantha_gpiomofo_display_lightboard_NativeLightBoard_setPoint
  (JNIEnv *, jobject, jint, jint, jboolean, jboolean);

/*
 * Class:     net_amarantha_gpiomofo_display_lightboard_NativeLightBoard
 * Method:    setPins
 * Signature: (IIIIIIIIIII)V
 */
JNIEXPORT void JNICALL Java_net_amarantha_gpiomofo_display_lightboard_NativeLightBoard_setPins
  (JNIEnv *, jobject, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     net_amarantha_gpiomofo_display_lightboard_NativeLightBoard
 * Method:    sleep
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_amarantha_gpiomofo_display_lightboard_NativeLightBoard_sleep
  (JNIEnv *, jobject);

/*
 * Class:     net_amarantha_gpiomofo_display_lightboard_NativeLightBoard
 * Method:    wake
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_amarantha_gpiomofo_display_lightboard_NativeLightBoard_wake
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
